### ISSUE TITLE
why is the Remote-User RequestHeader being unset here?

### ISSUE THREAD

**Issue by itewk** [openshift/request-header-saml-service-provider#12]
why is the Remote-User RequestHeader being unset here?

https://github.com/openshift/request-header-saml-service-provider/blob/d6f433769acaf58b7de0c18a6e99ab068083dafe/openshift.conf#L94

Wouldn't that undo https://github.com/openshift/request-header-saml-service-provider/blob/master/openshift.conf#L72 thus causing the Remote-User not to be set at all causing this entire thing not to work? (which in my case it is not right now)

**Comment by briantward** [comment]
I'm not certain it is ever doing anything, considering that this directive is outside of any functional VirtualHost blocks.  Perhaps it was here as some sort of failsafe or other test, if one were running many more VirtualHosts and Listening on other ports.  I think it can safely be removed.

**Comment by itewk** [comment]
@briantward want to make removing it part of the giant PR I know you have been working on?

**Comment by briantward** [comment]
@itewk sure will do...

**Comment by briantward** [comment]
@brenton This can be closed as it was corrected in PR #26
