### ISSUE TITLE
Create v1.0 release from 78e254c2333aa44d982feeb0af9842dbdcd87fdd

### ISSUE THREAD

**Issue by itewk** [openshift/request-header-saml-service-provider#30]
There was a major shift in this code base with https://github.com/openshift/request-header-saml-service-provider/pull/26 (https://github.com/openshift/request-header-saml-service-provider/commit/ed32fe3be77d78e1a9bef91adc5f96a7c12306a3)

We should tag the commit before that as v1.0 since we know from experience that the code and instructions there work. There may still be some kinks with the new documentation and code. Once we get those worked out we can tag a v2.0, and then once we get operator(s) we can tag v3.0.

Please tag/release 78e254c2333aa44d982feeb0af9842dbdcd87fdd (https://github.com/openshift/request-header-saml-service-provider/commit/78e254c2333aa44d982feeb0af9842dbdcd87fdd) with v1.0.

**Comment by itewk** [comment]
@brenton for your consideration.

**Comment by itewk** [comment]
@briantward FYI

**Comment by brenton** [comment]
done!

**Comment by itewk** [comment]
thank you @brenton
